[package]
name = "i2d-tree"
version = "0.1.0"
authors = ["Mark Shevchenko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.4.0"